### ISSUE TITLE
preprocessing

### ISSUE THREAD

**Issue by CaoJonas** [michaelmoju/ace05_ERE#2]
@michaelmoju Hello, I have dataset _tac-kbp-2017_, but I want to use _ace2005-preprocessing_ for preprocessing, Do you provide an _A.apf.xml_ file and an _A.sgm_ for me.

**Comment by michaelmoju** [comment]
I am not sure whether tac-kbp-2017 and ace2005 have the same format, but maybe you can check the preprocessing code I wrote in [ace05-parser](https://github.com/michaelmoju/ace05-parser)

**Comment by CaoJonas** [comment]
@michaelmoju Thanks. I'll try to run your code
